# Generated by Django 5.1.6 on 2025-02-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='vote',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
