# Generated by Django 5.1.6 on 2025-02-22 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Complaints', '0002_complaint_vote_alter_complaint_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domain',
            old_name='name',
            new_name='domain_name',
        ),
    ]
