# Generated by Django 5.1.6 on 2025-02-22 16:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Complaints', '0003_rename_name_domain_domain_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
